### ISSUE TITLE
Feature - Solana Wallet Connect

### ISSUE THREAD

**Issue by kenzoheye** [werate-io/werate-explorer#10]
## Solana Connect
Build out everything needed to connect to a Solana wallet within the front-end application. Display the currently connected wallet in the top right.

## Wallet linking
Allow the user to sign a transaction to prove they hold the private key of the connected wallet.
This signature should trigger our WeRate backend to link the solana wallet to the user (API does not exist yet, ask @kenzoheye to implement before starting development on the linking part

**Comment by verschaevesiebe** [comment]
Close upon request y @RateBuilder  as it was already merged.
