### ISSUE TITLE
Feature - Left Side Panel - Implement Review Statistics

### ISSUE THREAD

**Issue by kenzoheye** [werate-io/werate-explorer#6]
Add the left side panel for review statistics. Make sure at least this data is displayed:

- Total reviews
- Unique users
- Unique countries
- Unique businesses/venues
- rating scores (can be a graph/boxplot/bell curve)

**Comment by Talhaaa99** [comment]
@kenzoheye could you point me to the relavant apis for these

**Comment by Talhaaa99** [comment]
Got it kenzo, thanks
