### ISSUE TITLE
Feature - Right Side Panel - Implement User Statistics

### ISSUE THREAD

**Issue by kenzoheye** [werate-io/werate-explorer#7]
When a user is logged in, show a collapsible right side panel, which contains some user data/stats:

Can be retrieved from `GET /api/v1/users/me`:
- user ID
- user email
- nickname

Can be retrieved from `GET /api/v1/users/me/profile`
- wisdom
- reviewCount
- upvoteCount
- checkinCount
- uniqueVisitsCount
- avatarCount

**Comment by prabhanukash** [comment]
https://excalidraw.com/#room=4d1cbd422407c74b9045,MZ6rec2n6nzmW1tMjNezlA
