### ISSUE TITLE
Feature - Right Side Panel - Implement User Reviews

### ISSUE THREAD

**Issue by kenzoheye** [werate-io/werate-explorer#8]
When a User is logged in, in the right side panel they should be able to see a list of their reviews:

Data can be retrieved via:
- `GET /api/v1/game/players/reviews`

has pagination:
- skip is the amount of items to offset
- take is the amount of items in the current page

Make this a paginated list, infinite scroll or clicking through pages is both fine.

**Comment by prabhanukash** [comment]
@kenzoheye  here in the right side panel it should be reviews based on the location in the map?

**Comment by kenzoheye** [comment]
@prabhanukash it should be the reviews of the user when logged in, so login should be implemented first before this can be finished, but you can already mock the data coming from the /api/v1/game/players/reviews

Look here (mobile.werate.io)

**Comment by prabhanukash** [comment]
You're right, the login should be implemented first, as reviews are user-specific. However, I am able can mock the data from `/api/v1/game/players/reviews` for now from browser access token (nothing but login) to keep progress moving.

Let me know your thoughts!

![image](https://github.com/user-attachments/assets/c4f90eb4-821f-4dad-9b82-3d69fbfcc6af)
![image](https://github.com/user-attachments/assets/0496322f-ae12-42cb-8253-2d174d1ad507)

**Comment by kenzoheye** [comment]
Looks good! Please make a pull request and I will review your code

**Comment by prabhanukash** [comment]
feat/8/right-user-reviews https://github.com/werate-io/werate-explorer/pull/14/
